---
title: "Week 3 - Notes"
output:
  pdf_document: default
  html_document:
    df_print: paged
  html_notebook: default
---

# STRSPLIT
```{r}
mydata <- c("teste", "teste.2", "teste3")
mydata <- strsplit(mydata, "\\.")
firstElement <- function(x){x[1]}
results <- sapply(mydata , firstElement)
print(results)
```

# GSUB
```{r}
mydata <- c("teste", "teste.2", "teste3")          
mydata2 <- c("1,2", "1,3", "1,4")
mydata<-cbind(mydata,mydata2)
print(mydata)

mydata[,2] <- gsub(",",".",mydata[,2])
print(mydata)
```

# GREP
```{r}
mydata <- c("luiz", "fernando", "luizfernando")  
grep("fer",mydata)

```

# GREPL
```{r}
grepl("fer",mydata)
mydata3 <- mydata[grepl("fer",mydata)]
print(mydata3)
```

# Regular expressions I

^ - start of line
$ - end of line
[Bb][Uu][Ss][Hs] - looks for any bush word
^[Ii] am - looks for "I am" or "i am"
^[0-9][a-zA-Z] - any line that starts with number followed by character
[^?.]$ - not ending by ? or .

# Regular expressions II

9.11 - looks for any caracter between 9 and 11 ( "." means any character)
flood|fire - looks for both flood and fire
^([Gg]ood|[Bb]ad])
[Gg]eorge ([Ww]\.)? [Bb]ush - looks for any george bush with w in the middle or not (the \ is necessary because . is a special character)
(.*) - any character repeated
[0-9]+ (.*)[0-9]+  - at least one number followed by any number of characters followed by any number again
[Bb]ush( +[^ ]+ +){1,5} debate - bush  and at the end debate. in the middle at least one space followed by somehting that is not space repeated 1 to 5 times

 +([a-zA-Z]+) +\1 +
 
^s(.*)s - starts with s and ends with s

# Date class

```{r}
d2 <- Sys.Date()
d2
```

```{r}
format(d2, "%a %b %d")
format(d2, "%A %b %d")
```

```{r}

x <- c("1jan1960", "2jan1980", "3jul1980")
z <- as.Date(x, "%d%b%Y")
z
```







